- name: Install curl
  apt: name=curl state=latest

- name: deb
  shell: | 
    curl https://pkg.cloudflareclient.com/pubkey.gpg | gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list

- name: Update all packages
  apt: name="*" state=latest update_cache=true force_apt_get=true

- name: Install Cloudflare Warp
  apt: name=cloudflare-warp state=latest

- name: register
  command: warp-cli --accept-tos register

- name: set 
  shell: |
    warp-cli --accept-tos set-mode proxy
    warp-cli --accept-tos enable-always-on

- name : connect
  command: warp-cli --accept-tos connect
