- name: deb
  shell: | 
    curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list

- name: Update apt cache
  apt:
    update_cache: true

- name: Install Cloudflare Warp
  apt:
    name: cloudflare-warp
    state: present

- name: register
  command: warp-cli --accept-tos registration new

- name: set 
  shell: |
    warp-cli --accept-tos mode proxy

- name : connect
  command: warp-cli --accept-tos connect
